### PR TITLE
Run with it

### PR DESCRIPTION
**Pull request by zimbatm**
Taking #44 and going all the way.

TODO:
* [ ] Unit tests for the adapters
* [ ] Appengine compatibility

### CODE REVIEW

**Comment by jpatel531** [comment]
sweet! can i merge?

**Comment by leggetter** [comment]
If we are definitely happy to do so without testing some of the alternative adapters (the TODO above), sure.

I'd also like the peace of mind of some acceptance tests that actually hit the Pusher APIs.

But, we can create issues for both of these.

**Comment by jpatel531** [comment]
when i run the tests i'm getting:

AttributeError: 'module' object has no attribute 'create_default_context'
in sync.py ln 19

**Comment by zimbatm** [comment]
It definitely needs testing, looking for 30% feedback right now

**Comment by leggetter** [comment]
@jpatel531 What version of Python are you using?

**Comment by jpatel531** [comment]
I've now tried it on 3.4

It's coming out with: `bytes' object has no attribute 'encode'` - which is failing every test

**Comment by zimbatm** [comment]
It's still missing adapter tests. At this point the library has been tested manually against python 3.4.3, 2.7.2 and 2.6.7 with the various backends.

**Comment by jpatel531** [comment]
For some reason the change to the packages list is failing the tests - it's looking for the folders within the pusher directory. Is that normal?

**Comment by zimbatm** [comment]
Why python version ?

> it's looking for the folders within the pusher directory
 I'm not sure what that means

**Comment by jpatel531** [comment]
It was looking for the directory 'pusher/errors', 'pusher/aiohttp' etc.

**Comment by jpatel531** [comment]
ok @zimbatm - i've tested it out on GAE with a new urlfetch backend, for which tests have been added (mind you - all the backend adapters only test for trigger success). everything's green on travis. there's probably still some stuff to do (like more tests), but i'm happy to get this up on pypi as soon as possible. WDYT?

**Comment by zimbatm** [comment]
:shipit: :ship: :rocket:

**Pull request merged**
