### PR TITLE
Include cacert.pem as part of the package

### LINKED ISSUE #59: cacert.py
As i informed you in person, when i installed the library (not sure if it was from pip or easy_install), i got an error for missing the file "cacert.py", when i copied it from this repository, worked just fine.

### PR DESCRIPTION
**Pull request by zimbatm**
I'm not entirely sure but this should fix #59

### CODE REVIEW

**Comment by jpatel531** [comment]
Hmm I was a bit confused as to the issue the guy was having (he was at BattleHack Athens and playing around with the library). I have an intuition it might be a thing with Windows. Does python's `os` module work in the same way when finding paths on Windows? I'll have a look on a vm tomorrow

**Comment by zimbatm** [comment]
I think the file is just missing because it's not described in the setup.py. Did you try installing the lib trough pip and then issuing a request with the requests backend ?

**Comment by jpatel531** [comment]
Ah ****, you're right! Can I merge?

**Comment by jpatel531** [comment]
@zimbatm do we need a relative path, or will pip know?

**Comment by zimbatm** [comment]
Please test. You should be able to create the package and test the content, it's just a tarball I think

**Comment by jpatel531** [comment]
Will do!

**Comment by jpatel531** [comment]
Tested it and it's fine

**Comment by jpatel531** [comment]
Thanks @zimbatm - I didn't know about `package_data` at all!

**Pull request merged**
