### PR TITLE
Convenience method `validate_webhook_django()`

### PR DESCRIPTION
**Pull request by loisaidasam**
Plus corresponding documentation

### CODE REVIEW

**Comment by zimbatm** [comment]
What would you think of putting that method in a special module ?

```
from pusher.django import validate_webhook
webhook = validate_webhook(pusher, request)
```

**Comment by loisaidasam** [comment]
That's interesting, although I'd prefer not to have to import something else on the client side.

Perhaps I could add `request` as an optional parameter to `validate_webhook()`, and if provided have some sort of factory that figures out the class type of `request`, validating it accordingly..

**Comment by zimbatm** [comment]
Hi @loisaidasam ,

my concern is that if we start adding third-party code into the main module it would start accumulating a lot of methods that doesn't interest the other users. What about re-exporting all the normal pusher module exports so that `import pusher.django` would contain all the `pusher` exports plus the specific code to validate webhooks with django ?

Hope I'm not too much of a pain

**Comment by WillSewell** [comment]
I agree that we ideally do not want to start adding framework-specific functions to this library. The "correct" solution would be to create a wrapper around this library that is specialised to the Django framework, in a similar way to how pusher-http-laravel wraps pusher-http-python.

**Pull request closed without merging**
